// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: proto/employee_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EmployeeService_CreateEmployee_FullMethodName  = "/employee.EmployeeService/CreateEmployee"
	EmployeeService_SearchEmployees_FullMethodName = "/employee.EmployeeService/SearchEmployees"
	EmployeeService_CreateResume_FullMethodName    = "/employee.EmployeeService/CreateResume"
)

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	CreateEmployee(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*EmployeeCreatedReponse, error)
	SearchEmployees(ctx context.Context, in *SearchEmployeesRequest, opts ...grpc.CallOption) (EmployeeService_SearchEmployeesClient, error)
	CreateResume(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_CreateResumeClient, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) CreateEmployee(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*EmployeeCreatedReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployeeCreatedReponse)
	err := c.cc.Invoke(ctx, EmployeeService_CreateEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) SearchEmployees(ctx context.Context, in *SearchEmployeesRequest, opts ...grpc.CallOption) (EmployeeService_SearchEmployeesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[0], EmployeeService_SearchEmployees_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceSearchEmployeesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_SearchEmployeesClient interface {
	Recv() (*SearchEmployeesReponse, error)
	grpc.ClientStream
}

type employeeServiceSearchEmployeesClient struct {
	grpc.ClientStream
}

func (x *employeeServiceSearchEmployeesClient) Recv() (*SearchEmployeesReponse, error) {
	m := new(SearchEmployeesReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) CreateResume(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_CreateResumeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[1], EmployeeService_CreateResume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceCreateResumeClient{ClientStream: stream}
	return x, nil
}

type EmployeeService_CreateResumeClient interface {
	Send(*CreateResumeRequest) error
	CloseAndRecv() (*ResumeCreatedResponse, error)
	grpc.ClientStream
}

type employeeServiceCreateResumeClient struct {
	grpc.ClientStream
}

func (x *employeeServiceCreateResumeClient) Send(m *CreateResumeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceCreateResumeClient) CloseAndRecv() (*ResumeCreatedResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResumeCreatedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility
type EmployeeServiceServer interface {
	CreateEmployee(context.Context, *CreateEmployeeRequest) (*EmployeeCreatedReponse, error)
	SearchEmployees(*SearchEmployeesRequest, EmployeeService_SearchEmployeesServer) error
	CreateResume(EmployeeService_CreateResumeServer) error
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (UnimplementedEmployeeServiceServer) CreateEmployee(context.Context, *CreateEmployeeRequest) (*EmployeeCreatedReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployee not implemented")
}
func (UnimplementedEmployeeServiceServer) SearchEmployees(*SearchEmployeesRequest, EmployeeService_SearchEmployeesServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchEmployees not implemented")
}
func (UnimplementedEmployeeServiceServer) CreateResume(EmployeeService_CreateResumeServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateResume not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_CreateEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, req.(*CreateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_SearchEmployees_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchEmployeesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).SearchEmployees(m, &employeeServiceSearchEmployeesServer{ServerStream: stream})
}

type EmployeeService_SearchEmployeesServer interface {
	Send(*SearchEmployeesReponse) error
	grpc.ServerStream
}

type employeeServiceSearchEmployeesServer struct {
	grpc.ServerStream
}

func (x *employeeServiceSearchEmployeesServer) Send(m *SearchEmployeesReponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EmployeeService_CreateResume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).CreateResume(&employeeServiceCreateResumeServer{ServerStream: stream})
}

type EmployeeService_CreateResumeServer interface {
	SendAndClose(*ResumeCreatedResponse) error
	Recv() (*CreateResumeRequest, error)
	grpc.ServerStream
}

type employeeServiceCreateResumeServer struct {
	grpc.ServerStream
}

func (x *employeeServiceCreateResumeServer) SendAndClose(m *ResumeCreatedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceCreateResumeServer) Recv() (*CreateResumeRequest, error) {
	m := new(CreateResumeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmployee",
			Handler:    _EmployeeService_CreateEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchEmployees",
			Handler:       _EmployeeService_SearchEmployees_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateResume",
			Handler:       _EmployeeService_CreateResume_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/employee_service.proto",
}
