# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\"\n\x0eVerifyResponse\x12\x10\n\x08loggedIn\x18\x01 \x01(\x08\x32G\n\x0b\x41uthService\x12\x38\n\x0bVerifyToken\x12\x13.auth.VerifyRequest\x1a\x14.auth.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYREQUEST']._serialized_start=20
  _globals['_VERIFYREQUEST']._serialized_end=50
  _globals['_VERIFYRESPONSE']._serialized_start=52
  _globals['_VERIFYRESPONSE']._serialized_end=86
  _globals['_AUTHSERVICE']._serialized_start=88
  _globals['_AUTHSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
