version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/authdata

  redis:
    image: redis:latest
    container_name: redis-auth
    ports:
      - "3001:6379"
    volumes:
      - redis_data:/authdata

volumes:
  postgres_data:
  redis_data: