version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    ports:
      - "3000:5432"

  redis:
    image: redis:latest
    container_name: redis-auth
    ports:
      - "3001:6379"