version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-fetcher
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: sitemapDB
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis-fetcher
    ports:
      - "6379:6379"
